import { ComponentOverview } from '@/components/component-overview';
import { ThemeProvider } from '@/components/theme-provider';
import { GeistSans } from 'geist/font/sans';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={GeistSans.className}>
			<ThemeProvider attribute="class" defaultTheme="dark">
				<body className="antialiased mb-10 lg:mx-auto">
					<main className="container relative mx-auto mt-8 overflow-auto print:p-12">
						<ComponentOverview />
						{children}
					</main>
				</body>
			</ThemeProvider>
		</html>
	);
}
